# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1296384bc51e89f21fbce323abe67b85e84b57b61a1a2bb558c5df0bb2e7588b43d5e8e36cd9d75fe00834a5ed4abc863bf17034111ff29385be63c66435e97e

test:
  secret_key_base: 43f4356a9d3a6a9c9b97a32e64e411307c67030b76932b6b6e744bb55850b39a4ac195f39c6c98493393c2808d5264707be6f58e6d0e838f014bb2fc62f113a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
